services:
  db:
    image: mysql:latest
    container_name: mysql_server
    restart: always
    command: --innodb_redo_log_capacity=1073741824
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: my_project_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./ml-latest:/var/lib/mysql-files/ml-latest
      - ./personality-isf2018:/var/lib/mysql-files/personality-isf2018
      - ./user-system:/var/lib/mysql-files/user-system
    healthcheck:
      # mysqladmin ping checks if the engine is responsive
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword123"]
      interval: 5s   # Check every 5 seconds
      timeout: 5s    # Fail if no response in 5s
      retries: 10    # Give up after 10 failures
      start_period: 30s # Give MySQL 30s to initialize before first check

  app:
    build: .
    container_name: python_app
    depends_on:
      db:
        condition: service_healthy # The "Gatekeeper" logic
    ports:
      - "127.0.0.1:5001:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_SECRET_KEY=b539946948a1e777c1a0bab142b9b48887c838d81d050ce6
      - DATABASE_URL=mysql+pymysql://root:password123@db:3306/my_project_db
      - SECURITY_PEPPER=3daf86191e3f5805f8c20b2c82d0e911d406e9735d744ab7d4ba809f41dd83ce
  
  web:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

volumes:
  mysql_data:
